server:
  port: 8082

api:
  urls:
    TransfersChain: https://coreservicebus.izbank.ir/services/Pichak/TransfersChain
    chequeHolderInquiry: https://coreservicebus.izbank.ir/services/Pichak/ChequeHolderInquiry
    chequeIssuerInquiry: https://coreservicebus.izbank.ir/services/Pichak/ChequeIssuerInquiry
    camunda: https://ouomnibpms.izbank.ir/engine-rest
    deactivateHamoon: https://coreservicebus.izbank.ir/services/Pichak/Chakad
    getCustomerInfo: https://coreservicebus.izbank.ir/services/Customer/GetCustomerByCustomerNumberFromReport?customerNumber=
    getCustomerRelations: https://coreservicebus.izbank.ir/services/Customer/GetCustomerRelations
    GetCustomerByNationalCodeFromReport: https://coreservicebus.izbank.ir/services/Customer/GetCustomerByNationalCodeFromReport?nationalCode=
    transferCheque: https://coreservicebus.izbank.ir/services/Pichak/Transfer
    receiverInquiryCheque: https://coreservicebus.izbank.ir/services/Pichak/ReceiverInquiry
    saveChequeTransferStatus: https://coreservicebus.izbank.ir/services/Pichak/savestatus
    ownerAcceptChequeStatus: https://coreservicebus.izbank.ir/services/Pichak/OwnerChequeStatus
    receiverChequeKartabl: https://coreservicebus.izbank.ir/services/Pichak/chakad
    issuedChequeKartabl: https://iws.izbank.ir/Cheque/Chakad/GetRequests?CustomerNumber=
    saveIssueRequest: https://iws.izbank.ir/Cheque/chakad/SaveIssueRequest
    pichakAccept: https://coreservicebus.izbank.ir/services/Pichak/Accept
    caStatus: https://coreservicebus.izbank.ir/services/ca/Status
    caSign: https://coreservicebus.izbank.ir/services/ca/Sign
    GetChequeInquiry: https://coreservicebus.izbank.ir/services/sayad2/GetChequeInquiry?chequeSerial=
    postalCodeInquiry: https://coreservicebus.izbank.ir/services/inquiry/PostalInquiry?postalCode=
    saverequestCheque: https://iws.izbank.ir/Cheque/request/saverequest
    sendSMS: https://coreservicebus.izbank.ir/services/Notification/Sendsms
    #camunda: http://host.docker.internal:8081/engine-rest

errors:
  messages:
    USER_NOT_FOUND: "کاربر پیدا نشد"
    INVALID_EMAIL: "ایمیل نامعتبر است"
    GENERAL_ERROR: "خطای عمومی رخ داده است"
    CUSTOMER_IS_DE_ACTIVE: "مشتری غیرفعال می باشد"
    SERVICE_IS_UNAVAILABLE: "سرویس در دسترس نمی باشد"
    ERROR_SERVICE: "متاسفانه خطایی رخ داده است لطفا دقایقی دیگر تلاش نمایید"


